### ISSUE TITLE
Schema validation does not work in monaco editor

### ISSUE THREAD

**Issue by SebastianStamm** [camunda/element-templates-json-schema#56]
__Describe the Bug__

When using this schema with the monaco editor and enabling validation, certain errorMessages throw JS exceptions in the dev console.

__Steps to Reproduce__

1. Goto https://672q2q.csb.app/ (source code available here: https://codesandbox.io/s/element-templates-validation-monaco-672q2q?file=/src/index.js)
2. Hover over the version warning
3. Observe that the error message is correctly displayed
4. Hover over the documentationRef warning
5. Observe that the error message is not displayed
6. Check the browser console error log to see that an exception is thrown.

```text
errors.ts:22 Uncaught Error: t.message.replace is not a function

TypeError: t.message.replace is not a function
    at g (markers.ts:151:35)
    at Object.u [as makeKey] (markers.ts:123:10)
    at v.renderMarkerStatusbar (markerHoverParticipant.ts:188:86)
    at v.renderHoverParts (markerHoverParticipant.ts:101:8)
    at Bi._renderMessages (contentHover.ts:228:33)
    at Bi._withResult (contentHover.ts:193:9)
    at contentHover.ts:65:9
    at invoke (event.ts:554:17)
    at o.fire (event.ts:721:15)
    at b._fireResult (hoverOperation.ts:160:18)
    at b._setState (hoverOperation.ts:104:9)
    at b._triggerSyncComputation (hoverOperation.ts:144:8)
    at l.runner (hoverOperation.ts:62:89)
    at l.doRun (async.ts:503:9)
    at l.onTimeout (async.ts:497:9)
    at errors.ts:22:12
```

__Expected Behavior__

All error messages should work correctly.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 102
- OS: Windows 10
- Library version: 0.4.1

**Comment by SebastianStamm** [comment]
These errors are thrown for all properties where the `errorMessage` is not a string. So [this one](https://github.com/camunda/element-templates-json-schema/blob/5579ae200a7b00b8f73dcaaa9a36d3f8f027af10/packages/zeebe-element-templates-json-schema/resources/schema.json#L617-L622) breaks, but [this one](https://github.com/camunda/element-templates-json-schema/blob/5579ae200a7b00b8f73dcaaa9a36d3f8f027af10/packages/zeebe-element-templates-json-schema/resources/schema.json#L334) works.

**Comment by pinussilvestrus** [comment]
Maybe Monaco has some difficulties with [template strings](https://github.com/ajv-validator/ajv-errors#templates), which are supported by `ajv-errors` and we use heavily.

**Comment by MaxTru** [comment]
Proposing this for `ready`

**Comment by pinussilvestrus** [comment]
I will take this one and see what we can do. Maybe we should not use the `errorMessage` flavor in the base schema, but add them to our own [JS validator](https://github.com/bpmn-io/element-templates-validator).

The error messages are a custom keyword from [ajv-errors]( https://github.com/ajv-validator/ajv-errors) and we can't rely on that any JSON editor supports it. The schema could export these errors next to the schema via a separate file (so we can also use them in our tests).

I will sketch this one :+1:

**Comment by pinussilvestrus** [comment]
I just found out VSCode / Monaco is defining [`errorMessage` as its own (string!) keyword](https://github.com/microsoft/vscode/blob/c0769274fa136b45799edeccc0d0a2f645b75caf/src/vs/base/common/jsonSchema.ts#L79), which is definitely not the one from `ajv-errors`. Therefore, we should definitely get these things out of the base schemas.

**Comment by pinussilvestrus** [comment]
@SebastianStamm we just released a [new alpha version of the JSON Schema](https://www.npmjs.com/package/@camunda/zeebe-element-templates-json-schema/v/0.5.0-alpha.1) that fixes this problem. It should work as expected now, I verified it with [a fork of the CodeSandbox](https://codesandbox.io/s/element-templates-validation-monaco-forked-0u9elj?file=/src/index.js) you shared initially.
