### ISSUE TITLE
Let's make `Version` of type `integer` instead of `number`

### ISSUE THREAD

**Issue by Skaiir** [camunda/element-templates-json-schema#58]
__What should we do?__

Currently the schema considers a version of 2.15 as valid. This shouldn't be the case however, as we only allow integer versions as well as the timestamp which is still an int. 

This may cause confusion as our docs state correctly that we expect an int:
https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/defining-templates/

__Why should we do it?__

Change the type to integer, this will give proper syntax highlighting and avoid confusing scenarios especially for people trying to use two number semantic versioning.

**Comment by Skaiir** [comment]
Fixed here https://github.com/camunda/element-templates-json-schema/commit/1a746c88a88e953fa1a1ecd84023d4530c36093b

**Comment by nikku** [comment]
Still needs to be released @Skaiir.
